data <- read.csv("household_power_consumption.txt", header=TRUE,sep=";")
attach(data)
png(file = "plot2.png", height = 480, width = 480)
plot(Global_active_power, type="l", xlab="", xaxt = "n")
axis(1, at = c(1,length(Global_active_power)/2,length(Global_active_power)), labels = c("Thur","Fri","Sat"))
dev.off()